AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/migrate/**/
    - config.ru
    - tmp/**/*
    - log/**/*
    - vendor/**/*
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - lib/geister_protocol/*
