source 'https://rubygems.org'

group :default do
  gem 'rails', '~> 5.0.0'
  gem 'puma'
  gem 'active_model_serializers', '~> 0.10.0'
  gem 'json_world', '~> 0.2.3'
  gem 'rack-json_schema'
  gem 'json-schema'
  gem 'bcrypt'
  gem 'cancancan'
  gem 'rails-i18n'
  gem 'mysql2'
end

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-inline'
  gem 'pry-state'
  gem 'factory_girl_rails', '~> 4.5.0'
end

group :development do
  gem 'annotate'
  gem 'bullet'
  gem 'awesome_print'
  gem 'rubocop'
  gem 'guard-rubocop', require: false
  gem 'guard-rspec', require: false
  gem 'i18n_generators'
end

group :test do
  gem 'rspec', '~> 3.5.0'
  gem 'rspec-rails', '~> 3.5.0'
  gem 'shoulda-matchers', '~> 3.1.0', require: false
  gem 'rspec-json_matcher'
  gem 'database_cleaner'
  gem 'simplecov'
  gem 'rack-test'
  gem 'timecop'
end
